services:
  web:
    build: ./django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_backend/:/usr/src/django_backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=djangobackend

volumes:
  postgres_data:
