# Generated by Django 5.1.2 on 2024-11-02 23:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cliente_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('direccion_envio', models.CharField(max_length=255, verbose_name='Dirección de Envío')),
                ('preferencias_envio', models.TextField(blank=True, verbose_name='Preferencias de Envío')),
                ('historial_compras', models.JSONField(blank=True, default=dict, verbose_name='Historial de Compras')),
                ('fecha_ultima_compra', models.DateTimeField(blank=True, null=True, verbose_name='Última Compra')),
                ('total_compras', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total en Compras')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Clientes',
                'db_table': 'cliente_profiles',
            },
        ),
        migrations.CreateModel(
            name='TransportistaProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transportista_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('licencia', models.CharField(choices=[('A', 'Clase A'), ('B', 'Clase B'), ('C', 'Clase C'), ('D', 'Clase D')], max_length=50, verbose_name='Licencia')),
                ('numero_licencia', models.CharField(max_length=20, unique=True, verbose_name='Número de Licencia')),
                ('vehiculo', models.CharField(max_length=100, verbose_name='Vehículo')),
                ('zona_cobertura', models.TextField(verbose_name='Zona de Cobertura')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponible')),
                ('entregas_completadas', models.PositiveIntegerField(default=0, verbose_name='Entregas Completadas')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación Promedio')),
            ],
            options={
                'verbose_name': 'Perfil de Transportista',
                'verbose_name_plural': 'Perfiles de Transportistas',
                'db_table': 'transportista_profiles',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default='Sin Apellido', max_length=150, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='Usuario', max_length=150, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El número debe estar en formato: '+999999999'. Hasta 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Superusuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('client', 'Cliente'), ('transport', 'Transportista')], default='client', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
