# Generated by Django 5.1.2 on 2024-11-04 12:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_productos', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compras',
                'db_table': 'detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='ReporteEnvios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicial')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Final')),
                ('total_envios', models.PositiveIntegerField(default=0, verbose_name='Total de Envíos')),
                ('envios_completados', models.PositiveIntegerField(default=0, verbose_name='Envíos Completados')),
                ('envios_pendientes', models.PositiveIntegerField(default=0, verbose_name='Envíos Pendientes')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
            ],
            options={
                'verbose_name': 'Reporte de Envíos',
                'verbose_name_plural': 'Reportes de Envíos',
                'db_table': 'reporte_envios',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ReporteFinanciero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicial')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Final')),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Ventas')),
                ('total_envios', models.PositiveIntegerField(default=0, verbose_name='Total Envíos')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
            ],
            options={
                'verbose_name': 'Reporte Financiero',
                'verbose_name_plural': 'Reportes Financieros',
                'db_table': 'reporte_financiero',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_despacho', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventario.detallecompra', verbose_name='Compra')),
                ('transportista', models.ForeignKey(limit_choices_to={'role': 'transport'}, on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to=settings.AUTH_USER_MODEL, verbose_name='Transportista')),
            ],
            options={
                'verbose_name': 'Orden de Despacho',
                'verbose_name_plural': 'Órdenes de Despacho',
                'db_table': 'orden_despacho',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe tener al menos 3 caracteres')], verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventario.product', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='SeguimientoEnvio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('ubicacion_actual', models.CharField(blank=True, max_length=255, verbose_name='Ubicación Actual')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='inventario.ordendespacho', verbose_name='Orden de Despacho')),
            ],
            options={
                'verbose_name': 'Seguimiento de Envío',
                'verbose_name_plural': 'Seguimientos de Envíos',
                'db_table': 'seguimiento_envio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='StockVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_stock', models.PositiveIntegerField(verbose_name='Cantidad en Stock')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo de Actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_variables', to='inventario.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock Variable',
                'verbose_name_plural': 'Stock Variables',
                'db_table': 'stock_variable',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
