# Generated by Django 5.1.2 on 2024-11-03 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendespacho',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_despacho', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='inventario.detallecompra', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='transportista',
            field=models.ForeignKey(limit_choices_to={'role': 'transport'}, on_delete=django.db.models.deletion.PROTECT, related_name='transportes', to=settings.AUTH_USER_MODEL, verbose_name='Transportista'),
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='inventario.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='seguimientoenvio',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='inventario.ordendespacho', verbose_name='Orden de Despacho'),
        ),
        migrations.AddField(
            model_name='stockvariable',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_variables', to='inventario.product', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'categoria')},
        ),
    ]
