# Generated by Django 5.1.2 on 2024-11-02 00:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('users', '0002_cliente_transportista_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cantidad_productos', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Detalle Compra',
                'verbose_name_plural': 'Detalles Compra',
                'db_table': 'detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReporteFinanciero',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria_producto', models.CharField(max_length=100)),
                ('cantidad_vendida', models.IntegerField()),
                ('fecha_reporte', models.DateField()),
            ],
            options={
                'verbose_name': 'Reporte Financiero',
                'verbose_name_plural': 'Reportes Financieros',
                'db_table': 'reporte_financiero',
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='movimientostock',
            name='producto',
        ),
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.detallecompra')),
                ('id_tran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.transportista')),
            ],
            options={
                'verbose_name': 'Orden de Despacho',
                'verbose_name_plural': 'Órdenes de Despacho',
                'db_table': 'orden_despacho',
            },
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='inventario.product'),
        ),
        migrations.CreateModel(
            name='ReporteEnvios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_envios', models.IntegerField()),
                ('fecha_reporte', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
            ],
            options={
                'verbose_name': 'Reporte de Envío',
                'verbose_name_plural': 'Reportes de Envíos',
                'db_table': 'reporte_envios',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoEnvio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_envio', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('id_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ordendespacho')),
            ],
            options={
                'verbose_name': 'Seguimiento de Envío',
                'verbose_name_plural': 'Seguimientos de Envíos',
                'db_table': 'seguimiento_envio',
            },
        ),
        migrations.CreateModel(
            name='StockVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_stock', models.IntegerField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_variables', to='inventario.product')),
            ],
            options={
                'verbose_name': 'Stock Variable',
                'verbose_name_plural': 'Stock Variables',
                'db_table': 'stock_variable',
            },
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='MovimientoStock',
        ),
    ]
