# Generated by Django 5.1.2 on 2024-11-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordendespacho',
            name='compra',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ManyToManyField(related_name='detalles_compra', to='inventario.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='compra',
            field=models.ManyToManyField(related_name='ordenes', to='inventario.detallecompra', verbose_name='Compra'),
        ),
    ]
