# Generated by Django 5.1.2 on 2024-11-04 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe tener al menos 3 caracteres')], verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'categoria')},
        ),
    ]
