# Generated by Django 5.1.3 on 2024-11-24 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_envio', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='tiempo_salida_aprox',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiempo Aproximado de Salida'),
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordendespacho',
            name='compra',
        ),
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.envio')),
            ],
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ManyToManyField(related_name='detalles_compra', to='inventario.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='ordendespacho',
            name='compra',
            field=models.ManyToManyField(related_name='ordenes', to='inventario.detallecompra', verbose_name='Compra'),
        ),
    ]
