
# Generated by Django 5.1.3 on 2024-11-17 02:29
# Generated by Django 5.1.2 on 2024-11-22 00:41


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_envio', models.DateField()),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='inventario.envio')),
            ],
        ),
    ]
