# Generated by Django 5.1.2 on 2024-11-02 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_detallecompra_product_reportefinanciero_and_more'),
        ('ventas', '0002_alter_detalleventa_producto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
