# Generated by Django 5.1.2 on 2024-11-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_detallecompra_product_reporteenvios_and_more'),
        ('ventas', '0002_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
