# Generated by Django 5.1.2 on 2024-11-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_envio_estadoenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
