# Generated by Django 5.1.2 on 2024-11-04 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_product_name_alter_product_unique_together'),
        ('inventario', '0002_initial'),
    ]

    operations = [
    ]
