# Generated by Django 5.1.3 on 2024-11-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_envio_estadoenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendespacho',
            name='tiempo_salida_aprox',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiempo Aproximado de Salida'),
        ),
    ]
