# Generated by Django 5.1.3 on 2024-11-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_despacho_detalledespacho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalledespacho',
            options={'verbose_name': 'Detalle de Despacho', 'verbose_name_plural': 'Detalles de Despacho'},
        ),
        migrations.AlterField(
            model_name='detalledespacho',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detalledespacho',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
